/* ============================================================
   Keigo — Business Japanese curriculum
   Japanese is authored with inline furigana syntax: {漢字|reading}
   Everything outside braces renders as-is (kana, punctuation).
   ============================================================ */

window.CURRICULUM = {
  modules: [
    {
      id: "greetings",
      kicker: "Module 01",
      title: "Greetings",
      jp: "挨拶",
      blurb: "First impressions, self-introductions, and the choreography of the business bow.",
      subtopics: ["greet-self", "greet-daily"],
    },
    {
      id: "meetings",
      kicker: "Module 02",
      title: "Meetings",
      jp: "会議",
      blurb: "Leading, joining, and politely disagreeing in the conference room.",
      subtopics: ["meet-open", "meet-opinion"],
    },
    {
      id: "email",
      kicker: "Module 03",
      title: "E-Mail",
      jp: "メール",
      blurb: "The unwritten rules of the Japanese business inbox: openings, cushioning language, and graceful sign-offs.",
      accentHint: "#e8a13a",
      subtopics: ["email-openings", "email-vocab", "email-closings"],
    },
    {
      id: "phone",
      kicker: "Module 04",
      title: "Phone & Keigo",
      jp: "電話・敬語",
      blurb: "Honorific and humble speech where you can't rely on body language.",
      subtopics: ["phone-basics", "phone-keigo"],
    },
  ],

  subtopics: {
    "email-openings": {
      moduleId: "email",
      index: 1,
      total: 3,
      title: "Email Openings",
      jp: "{書|か}き{出|だ}し",
      summary: "How to begin: before you've said anything at all.",
      cards: [
        {
          type: "intro",
          kicker: "Email · Openings",
          title: "Before the first word",
          body: "A Japanese business email almost never opens with the message. It opens with a ritual greeting that signals your relationship to the reader. Choosing the wrong one reads as either cold or presumptuous. Three openers cover ~90% of situations. Let's make them automatic.",
          meta: "4 phrases · 2 examples · 1 check",
        },
        {
          type: "concept",
          kicker: "The rule",
          title: "Match the opener to the relationship",
          points: [
            { k: "External / client", v: "Your default for anyone outside the company: いつもお世話になっております。" },
            { k: "Internal / colleague", v: "For teammates, any time of day: お疲れ様です。" },
            { k: "First-ever contact", v: "When they don't yet know you: 突然のご連絡失礼いたします。" },
          ],
          note: "Then immediately identify yourself: 〇〇株式会社の田中です。",
        },
        {
          type: "vocab",
          kicker: "Phrase 1 of 4",
          jp: "いつも{お世話|おせわ}になっております。",
          romaji: "Itsumo osewa ni natte orimasu.",
          en: "“Thank you for your continued support.”",
          literal: "Lit. “You are always taking care of (us).”",
          usage: "The universal external opener. Don't read it literally. It is a relationship marker, not gratitude for a specific thing. Use it even in a first reply of the day to a known client.",
          tag: "External",
        },
        {
          type: "vocab",
          kicker: "Phrase 2 of 4",
          jp: "お{疲|つか}れ{様|さま}です。",
          romaji: "Otsukare-sama desu.",
          en: "“Thanks for your hard work.” (internal greeting)",
          literal: "Lit. “You are honorably tired.”",
          usage: "The internal counterpart. Acceptable morning, noon, or night. Never use お世話 with your own teammates. It sounds oddly distant.",
          tag: "Internal",
        },
        {
          type: "vocab",
          kicker: "Phrase 3 of 4",
          jp: "{突然|とつぜん}のご{連絡|れんらく}{失礼|しつれい}いたします。",
          romaji: "Totsuzen no go-renraku shitsurei itashimasu.",
          en: "“Please excuse my contacting you out of the blue.”",
          literal: "Lit. “I commit the rudeness of a sudden contact.”",
          usage: "Opens a cold email to someone who has no prior relationship with you. Pair it with how you found them: 〇〇様よりご紹介いただきました。",
          tag: "Cold contact",
        },
        {
          type: "vocab",
          kicker: "Phrase 4 of 4",
          jp: "ご{無沙汰|ぶさた}しております。",
          romaji: "Go-busata shite orimasu.",
          en: "“It's been a while.” (apologetic)",
          literal: "Lit. “I have been negligent (in keeping in touch).”",
          usage: "Re-opening contact after months of silence. Carries a faint apology for the gap, warmer than restarting with お世話.",
          tag: "Reconnecting",
        },
        {
          type: "dialogue",
          kicker: "In context",
          title: "A reply to a known client",
          speakerA: "佐藤 (you)",
          speakerB: "",
          lines: [
            { who: "open", jp: "{山田|やまだ}{部長|ぶちょう}", role: "To" },
            { who: "a", jp: "いつも{お世話|おせわ}になっております。", note: "Opener: relationship marker" },
            { who: "a", jp: "{株式会社|かぶしきがいしゃ}アオイの{佐藤|さとう}です。", note: "Self-identify: company → name" },
            { who: "a", jp: "{先日|せんじつ}はお{時間|じかん}をいただき、ありがとうございました。", note: "Bridge into the actual message" },
          ],
          caption: "Notice the order: greeting → who you are → a thread back to your last contact. Only then does the real content begin.",
        },
        {
          type: "email",
          kicker: "Worked example",
          title: "A thank-you after a meeting",
          to: "{山田|やまだ}{部長|ぶちょう}",
          subject: "{先日|せんじつ}のお{打|う}ち{合|あ}わせのお{礼|れい}",
          body: [
            { jp: "{山田|やまだ}{部長|ぶちょう}", },
            { jp: "いつも{お世話|おせわ}になっております。", hi: true },
            { jp: "{株式会社|かぶしきがいしゃ}アオイの{佐藤|さとう}です。", hi: true },
            { jp: "" },
            { jp: "{先日|せんじつ}はお{忙|いそが}しい{中|なか}、お{時間|じかん}をいただき、{誠|まこと}にありがとうございました。" },
            { jp: "ご{提案|ていあん}いただいた{件|けん}、{社内|しゃない}で{前向|まえむ}きに{検討|けんとう}しております。" },
            { jp: "{取|と}り{急|いそ}ぎ、お{礼|れい}{申|もう}し{上|あ}げます。", hi: true },
          ],
          signature: [
            "{株式会社|かぶしきがいしゃ}アオイ　{営業部|えいぎょうぶ}",
            "{佐藤|さとう}{太郎|たろう}",
          ],
          caption: "The opener いつもお世話になっております establishes the relationship, the self-introduction follows immediately, and 取り急ぎ flags that this is a brief note of thanks.",
        },
        {
          type: "quiz-mc",
          kicker: "Quick check",
          q: "You're emailing a teammate in your own department about lunch logistics. Which opener fits?",
          jpContext: null,
          options: [
            { jp: "お{疲|つか}れ{様|さま}です。", correct: true },
            { jp: "いつも{お世話|おせわ}になっております。", correct: false },
            { jp: "{突然|とつぜん}のご{連絡|れんらく}{失礼|しつれい}いたします。", correct: false },
          ],
          explain: "お疲れ様です is the internal greeting. お世話になっております would sound strangely formal to a colleague, and the 突然 opener is only for people who don't know you.",
        },
      ],
    },

    "email-vocab": {
      moduleId: "email",
      index: 2,
      total: 3,
      title: "Email Vocabulary",
      jp: "ビジネス{語彙|ごい}",
      summary: "Cushioning language that makes a request land softly.",
      cards: [
        {
          type: "intro",
          kicker: "Email · Vocabulary",
          title: "The art of the soft request",
          body: "Japanese business writing rarely asks for something directly. Instead it pads the request with クッション言葉 (“cushion words”) that acknowledge the burden you're placing on the reader before you place it. Master five of these and your emails instantly read as native-polite.",
          meta: "5 phrases · 1 example · 1 check",
        },
        {
          type: "concept",
          kicker: "The rule",
          title: "Cushion → request → gratitude",
          points: [
            { k: "1 · Cushion", v: "Acknowledge the imposition: お忙しいところ恐れ入りますが…" },
            { k: "2 · Request", v: "State it plainly but in 謙譲語: 〜していただけますでしょうか。" },
            { k: "3 · Close the loop", v: "ご確認のほどよろしくお願いいたします。" },
          ],
          note: "The cushion is not optional politeness: omitting it is what reads as rude.",
        },
        {
          type: "vocab",
          kicker: "Phrase 1 of 5",
          jp: "お{忙|いそが}しいところ{恐|おそ}れ{入|い}りますが",
          romaji: "O-isogashii tokoro osore-irimasu ga",
          en: "“I'm sorry to trouble you when you're busy, but…”",
          literal: "Lit. “At a busy time, I am awe-struck (to ask), but…”",
          usage: "The premium cushion before any request. The trailing が leaves the sentence open, leading into what you need.",
          tag: "Cushion",
        },
        {
          type: "vocab",
          kicker: "Phrase 2 of 5",
          jp: "お{手数|てすう}をおかけしますが",
          romaji: "O-tesū o o-kake shimasu ga",
          en: "“Sorry for the inconvenience, but…”",
          literal: "Lit. “I am causing you trouble/effort, but…”",
          usage: "Use when your request will make the reader actually do something: fill a form, resend a file, check a date.",
          tag: "Cushion",
        },
        {
          type: "vocab",
          kicker: "Phrase 3 of 5",
          jp: "ご{査収|さしゅう}ください。",
          romaji: "Go-sashū kudasai.",
          en: "“Please find the attached / kindly check it over.”",
          literal: "Lit. “Please inspect and receive.”",
          usage: "Specifically for attachments or enclosed materials you want the reader to review and keep. Don't use it for things with nothing attached.",
          tag: "Attachments",
        },
        {
          type: "vocab",
          kicker: "Phrase 4 of 5",
          jp: "{取|と}り{急|いそ}ぎご{連絡|れんらく}まで。",
          romaji: "Tori-isogi go-renraku made.",
          en: "“A quick note for now.”",
          literal: "Lit. “In haste, just (this) contact.”",
          usage: "A sign-off for a short, urgent heads-up: signals you'll follow up properly later. Slightly informal; fine for known contacts.",
          tag: "Sign-off",
        },
        {
          type: "vocab",
          kicker: "Phrase 5 of 5",
          jp: "ご{確認|かくにん}のほどよろしくお{願|ねが}いいたします。",
          romaji: "Go-kakunin no hodo yoroshiku o-negai itashimasu.",
          en: "“I'd appreciate it if you could confirm.”",
          literal: "Lit. “Regarding (your) confirmation, I respectfully request.”",
          usage: "Closes a request loop. The のほど softens 確認 from a command into a gentle ask: more polite than ご確認ください。",
          tag: "Closing a loop",
        },
        {
          type: "email",
          kicker: "Worked example",
          title: "Requesting a quote",
          to: "{鈴木|すずき}{様|さま}",
          subject: "{見積書|みつもりしょ}ご{送付|そうふ}のお{願|ねが}い",
          body: [
            { jp: "{鈴木|すずき}{様|さま}" },
            { jp: "いつも{お世話|おせわ}になっております。" },
            { jp: "{株式会社|かぶしきがいしゃ}アオイの{佐藤|さとう}です。" },
            { jp: "" },
            { jp: "お{忙|いそが}しいところ{恐|おそ}れ{入|い}りますが、", hi: true },
            { jp: "{先日|せんじつ}ご{相談|そうだん}した{件|けん}の{見積書|みつもりしょ}をご{送付|そうふ}いただけますでしょうか。" },
            { jp: "お{手数|てすう}をおかけしますが、{今週中|こんしゅうちゅう}にご{確認|かくにん}いただけますと{幸|さいわ}いです。", hi: true },
            { jp: "{何卒|なにとぞ}よろしくお{願|ねが}いいたします。" },
          ],
          signature: [
            "{株式会社|かぶしきがいしゃ}アオイ　{営業部|えいぎょうぶ}　{佐藤|さとう}{太郎|たろう}",
          ],
          caption: "Two cushion phrases do the heavy lifting: お忙しいところ恐れ入りますが opens the request, and お手数をおかけしますが softens the follow-up ask.",
        },
        {
          type: "quiz-match",
          kicker: "Quick check",
          q: "Match each phrase to the moment it fits.",
          pairs: [
            { jp: "ご{査収|さしゅう}ください。", en: "There's a file attached" },
            { jp: "お{手数|てすう}をおかけしますが", en: "Before asking them to redo something" },
            { jp: "{取|と}り{急|いそ}ぎご{連絡|れんらく}まで。", en: "A fast heads-up, more to come" },
          ],
          explain: "査収 = inspect & keep (attachments). 手数 = the effort you're asking of them. 取り急ぎ flags brevity and a promise to follow up.",
        },
      ],
    },

    "email-closings": {
      moduleId: "email",
      index: 3,
      total: 3,
      title: "Email Closings",
      jp: "{結|むす}び",
      summary: "Sign off with the right weight of formality.",
      cards: [
        {
          type: "intro",
          kicker: "Email · Closings",
          title: "Landing the email",
          body: "The closing is where formality is calibrated most finely. The same idea (“thanks, regards”) has a ladder of forms from everyday to ceremonial. Pick the rung that matches your reader and the stakes of the message.",
          meta: "4 phrases · 1 example · 1 check",
        },
        {
          type: "concept",
          kicker: "The rule",
          title: "A ladder of formality",
          points: [
            { k: "Everyday", v: "Safe in almost any business email: よろしくお願いいたします。" },
            { k: "Formal", v: "For clients, superiors, and high stakes: 何卒よろしくお願い申し上げます。" },
            { k: "Ongoing", v: "When the relationship continues: 引き続きよろしくお願いいたします。" },
          ],
          note: "申し上げます is the humble form of 言う/する: it raises the reader by lowering you.",
        },
        {
          type: "vocab",
          kicker: "Phrase 1 of 4",
          jp: "よろしくお{願|ねが}いいたします。",
          romaji: "Yoroshiku o-negai itashimasu.",
          en: "“Thank you in advance. / Best regards.”",
          literal: "Lit. “I respectfully ask for your favor.”",
          usage: "The workhorse closing. いたします (humble する) makes it appropriately deferential for nearly all business mail.",
          tag: "Everyday",
        },
        {
          type: "vocab",
          kicker: "Phrase 2 of 4",
          jp: "{何卒|なにとぞ}よろしくお{願|ねが}い{申|もう}し{上|あ}げます。",
          romaji: "Nanitozo yoroshiku o-negai mōshi-agemasu.",
          en: "“I sincerely ask for your kind consideration.”",
          literal: "Lit. “By all means, I humbly make this request.”",
          usage: "The formal rung. 何卒 adds gravity; 申し上げます is maximally humble. Reserve for clients, executives, apologies, or important asks.",
          tag: "Formal",
        },
        {
          type: "vocab",
          kicker: "Phrase 3 of 4",
          jp: "{引|ひ}き{続|つづ}きよろしくお{願|ねが}いいたします。",
          romaji: "Hiki-tsuzuki yoroshiku o-negai itashimasu.",
          en: "“Thank you for your continued support.”",
          literal: "Lit. “Continuing on, I ask for your favor.”",
          usage: "For an ongoing relationship or project. It signals that contact won't end with this email.",
          tag: "Ongoing",
        },
        {
          type: "vocab",
          kicker: "Phrase 4 of 4",
          jp: "ご{検討|けんとう}のほどよろしくお{願|ねが}いいたします。",
          romaji: "Go-kentō no hodo yoroshiku o-negai itashimasu.",
          en: "“I look forward to your consideration.”",
          literal: "Lit. “Regarding your consideration, I respectfully ask.”",
          usage: "Closes a proposal or request that needs the reader to think and decide: a quote, a meeting time, an offer.",
          tag: "Proposals",
        },
        {
          type: "email",
          kicker: "Worked example",
          title: "Closing a proposal",
          to: "{田中|たなか}{様|さま}",
          subject: "{新|しん}サービスのご{提案|ていあん}",
          body: [
            { jp: "{田中|たなか}{様|さま}" },
            { jp: "{平素|へいそ}より{大変|たいへん}{お世話|おせわ}になっております。" },
            { jp: "{株式会社|かぶしきがいしゃ}アオイの{佐藤|さとう}でございます。" },
            { jp: "" },
            { jp: "{標記|ひょうき}の{件|けん}につきまして、{資料|しりょう}をお{送|おく}りいたします。" },
            { jp: "ご{査収|さしゅう}のうえ、ご{検討|けんとう}いただけますと{幸|さいわ}いです。" },
            { jp: "" },
            { jp: "ご{検討|けんとう}のほど、よろしくお{願|ねが}いいたします。", hi: true },
            { jp: "{引|ひ}き{続|つづ}きよろしくお{願|ねが}いいたします。", hi: true },
          ],
          signature: [
            "{株式会社|かぶしきがいしゃ}アオイ　{営業部|えいぎょうぶ}　{佐藤|さとう}{太郎|たろう}",
          ],
          caption: "The closing stacks two rungs: ご検討のほど invites a decision on the proposal, and 引き続き signals the relationship continues beyond this email.",
        },
        {
          type: "quiz-arrange",
          kicker: "Quick check",
          q: "Tap the pieces in order to build the formal closing.",
          target: ["{何卒|なにとぞ}", "よろしく", "お{願|ねが}い", "{申|もう}し{上|あ}げます。"],
          romaji: "Nanitozo yoroshiku o-negai mōshi-agemasu.",
          en: "“I sincerely ask for your kind consideration.”",
          explain: "何卒 → よろしく → お願い → 申し上げます。 The humble 申し上げます is what lifts this above the everyday いたします closing.",
        },
      ],
    },

    "greet-self": {
      moduleId: "greetings",
      index: 1,
      total: 2,
      title: "Self-Introductions",
      jp: "{自己|じこ}{紹介|しょうかい}",
      summary: "The first ninety seconds, and the card exchange that frames them.",
      cards: [
        {
          type: "intro",
          kicker: "Greetings · Self-intro",
          title: "The first ninety seconds",
          body: "A Japanese introduction is choreography: a bow, an exchange of cards, and a fixed verbal formula. Get the order and the humility level right and you signal that you know how this works, which matters more than fluency.",
          meta: "4 phrases · 1 example · 1 check",
        },
        {
          type: "concept",
          kicker: "The rule",
          title: "Company, then department, then you",
          points: [
            { k: "Order", v: "Name your company first, your role second, yourself last: 株式会社アオイの佐藤です。" },
            { k: "Humble form", v: "Use と申します rather than です to lower yourself politely." },
            { k: "Close", v: "Always seal it with よろしくお願いいたします。" },
          ],
          note: "You lower yourself and your company; you never elevate either in front of the other party.",
        },
        {
          type: "vocab",
          kicker: "Phrase 1 of 4",
          jp: "はじめまして。",
          romaji: "Hajimemashite.",
          en: "“How do you do.”",
          literal: "Lit. “(We are meeting) for the first time.”",
          usage: "Opens a genuine first meeting, said just before you give your name. Don't use it with someone you've emailed before but never met in person; ご挨拶が遅れましたfits better there.",
          tag: "First meeting",
        },
        {
          type: "vocab",
          kicker: "Phrase 2 of 4",
          jp: "{株式会社|かぶしきがいしゃ}アオイの{佐藤|さとう}と{申|もう}します。",
          romaji: "Kabushiki-gaisha Aoi no Sato to mōshimasu.",
          en: "“My name is Sato, from Aoi Inc.”",
          literal: "Lit. “I am called Sato of Aoi Inc.”",
          usage: "と申します is the humble form of と言います. Lead with the company, attach の, then your surname. Given names are rarely used in business.",
          tag: "謙譲語",
        },
        {
          type: "vocab",
          kicker: "Phrase 3 of 4",
          jp: "{名刺|めいし}を{頂戴|ちょうだい}してもよろしいでしょうか。",
          romaji: "Meishi o chōdai shitemo yoroshii deshō ka.",
          en: "“May I have your business card?”",
          literal: "Lit. “Would it be acceptable to receive your card?”",
          usage: "Receive a card with both hands, read it, and place it on the table, not straight into your pocket. 頂戴する is humbler than もらう.",
          tag: "Card exchange",
        },
        {
          type: "vocab",
          kicker: "Phrase 4 of 4",
          jp: "{以後|いご}お{見知|みし}りおきください。",
          romaji: "Igo o-mishiri-oki kudasai.",
          en: "“Please keep me in mind from now on.”",
          literal: "Lit. “Please be acquainted with me hereafter.”",
          usage: "A slightly formal flourish to end an introduction, common when you hope to do business again. Optional, but it lands well with senior contacts.",
          tag: "Formal flourish",
        },
        {
          type: "dialogue",
          kicker: "In context",
          title: "Exchanging cards",
          speakerA: "佐藤",
          speakerB: "",
          lines: [
            { who: "a", jp: "はじめまして。{株式会社|かぶしきがいしゃ}アオイの{佐藤|さとう}と{申|もう}します。", note: "Greeting then company and name" },
            { who: "a", jp: "{名刺|めいし}を{頂戴|ちょうだい}してもよろしいでしょうか。", note: "Requesting the card" },
            { who: "a", jp: "ありがとうございます。{以後|いご}よろしくお{願|ねが}いいたします。", note: "Receiving, then sealing it" },
          ],
          caption: "Notice the fixed sequence: greet, identify, request the card, close. The same script works in almost any first meeting.",
        },
        {
          type: "quiz-mc",
          kicker: "Quick check",
          q: "You're giving your own name to a new client. Which form is appropriately humble?",
          options: [
            { jp: "{佐藤|さとう}と{申|もう}します。", correct: true },
            { jp: "{佐藤|さとう}です。", correct: false },
            { jp: "{佐藤|さとう}とおっしゃいます。", correct: false },
          ],
          explain: "と申します is the humble form for your own name. です is fine but less polished; おっしゃる is honorific and is only ever used about the other person, never yourself.",
        },
      ],
    },

    "greet-daily": {
      moduleId: "greetings",
      index: 2,
      total: 2,
      title: "Daily Office Greetings",
      jp: "{日々|ひび}の{挨拶|あいさつ}",
      summary: "The small phrases that mark every transition of the workday.",
      cards: [
        {
          type: "intro",
          kicker: "Greetings · Daily",
          title: "The rhythm of the day",
          body: "Japanese offices run on a handful of greetings that mark arriving, passing in the hall, and leaving. They're almost reflexive, but using the wrong one, or skipping one, reads as cold. These four carry most days.",
          meta: "4 phrases · 1 example · 1 check",
        },
        {
          type: "concept",
          kicker: "The rule",
          title: "Greetings mark transitions",
          points: [
            { k: "Arriving", v: "おはようございます is the morning arrival greeting, sometimes used all day on first contact." },
            { k: "In passing", v: "お疲れ様です acknowledges a colleague any time, in the hall or in chat." },
            { k: "Leaving", v: "お先に失礼します when you leave before others; お疲れ様でした in reply." },
          ],
          note: "お疲れ様です is internal only. To clients you still use お世話になっております.",
        },
        {
          type: "vocab",
          kicker: "Phrase 1 of 4",
          jp: "おはようございます。",
          romaji: "Ohayō gozaimasu.",
          en: "“Good morning.”",
          literal: "Lit. “It is early.” (honorific)",
          usage: "The arrival greeting. In many industries (media, hospitality) it's used as the first-contact greeting at any hour, not just the morning.",
          tag: "Arriving",
        },
        {
          type: "vocab",
          kicker: "Phrase 2 of 4",
          jp: "お{先|さき}に{失礼|しつれい}します。",
          romaji: "O-saki ni shitsurei shimasu.",
          en: "“Excuse me for leaving first.”",
          literal: "Lit. “I commit the rudeness of going ahead.”",
          usage: "Said when you leave the office while others are still working. The standard reply from them is お疲れ様でした。",
          tag: "Leaving",
        },
        {
          type: "vocab",
          kicker: "Phrase 3 of 4",
          jp: "{承知|しょうち}いたしました。",
          romaji: "Shōchi itashimashita.",
          en: "“Understood. / Certainly.”",
          literal: "Lit. “I have humbly comprehended.”",
          usage: "Accepts an instruction from a client or superior. Clearly humbler than わかりました, which can sound flat to someone senior.",
          tag: "Acknowledging",
        },
        {
          type: "vocab",
          kicker: "Phrase 4 of 4",
          jp: "{恐|おそ}れ{入|い}ります。",
          romaji: "Osore-irimasu.",
          en: "“Thank you. / Excuse me.” (deferential)",
          literal: "Lit. “I am filled with awe.”",
          usage: "A versatile word that mixes thanks and apology: use it when someone does you a small favour, or to soften getting their attention.",
          tag: "All-purpose",
        },
        {
          type: "dialogue",
          kicker: "In context",
          title: "Leaving for the day",
          speakerA: "あなた / 同僚",
          speakerB: "",
          lines: [
            { who: "open", jp: "{定時|ていじ}、{退社|たいしゃ}", role: "Scene" },
            { who: "a", jp: "お{先|さき}に{失礼|しつれい}します。", note: "You, leaving first" },
            { who: "a", jp: "お{疲|つか}れ{様|さま}でした。{気|き}をつけて。", note: "Colleague, in reply" },
          ],
          caption: "The pair お先に失礼します → お疲れ様でした is a near-fixed exchange. Past tense でした marks that the day's work is done.",
        },
        {
          type: "quiz-match",
          kicker: "Quick check",
          q: "Match each greeting to its moment.",
          pairs: [
            { jp: "おはようございます。", en: "Arriving at the office" },
            { jp: "お{先|さき}に{失礼|しつれい}します。", en: "Leaving before colleagues" },
            { jp: "{承知|しょうち}いたしました。", en: "Accepting an instruction" },
          ],
          explain: "おはよう marks arrival, お先に失礼 marks your early departure, and 承知いたしました humbly accepts a request.",
        },
      ],
    },

    "meet-open": {
      moduleId: "meetings",
      index: 1,
      total: 2,
      title: "Opening a Meeting",
      jp: "{会議|かいぎ}を{始|はじ}める",
      summary: "Thanking the room, framing the agenda, and inviting questions.",
      cards: [
        {
          type: "intro",
          kicker: "Meetings · Opening",
          title: "Setting the room in motion",
          body: "Whoever opens a Japanese meeting follows a short ritual: thank people for their time, lay out the agenda, then hand the floor over. It signals respect for everyone's schedule and gives the meeting a clear shape.",
          meta: "4 phrases · 1 example · 1 check",
        },
        {
          type: "concept",
          kicker: "The rule",
          title: "Thank, frame, then open the floor",
          points: [
            { k: "Thank", v: "本日はお忙しい中、お集まりいただきありがとうございます。" },
            { k: "Frame", v: "State how many items there are: 本日の議題は三つございます。" },
            { k: "Open", v: "Invite participation: 何かご質問はございますか。" },
          ],
          note: "ございます is the polite existential; it raises the register of an otherwise plain statement.",
        },
        {
          type: "vocab",
          kicker: "Phrase 1 of 4",
          jp: "それでは、{始|はじ}めさせていただきます。",
          romaji: "Sore dewa, hajimesasete itadakimasu.",
          en: "“Well then, allow me to begin.”",
          literal: "Lit. “I humbly receive the favour of being allowed to start.”",
          usage: "〜させていただく frames your own action as something the room permits. It's the standard humble way to start proceedings.",
          tag: "Starting",
        },
        {
          type: "vocab",
          kicker: "Phrase 2 of 4",
          jp: "{本日|ほんじつ}はお{忙|いそが}しい{中|なか}お{集|あつ}まりいただき、ありがとうございます。",
          romaji: "Honjitsu wa o-isogashii naka o-atsumari itadaki, arigatō gozaimasu.",
          en: "“Thank you all for gathering despite your busy schedules.”",
          literal: "Lit. “Amid your busyness today, thank you for assembling.”",
          usage: "本日 is the formal word for 今日. The お忙しい中 cushion mirrors the one you use in email openings.",
          tag: "Thanking",
        },
        {
          type: "vocab",
          kicker: "Phrase 3 of 4",
          jp: "{本日|ほんじつ}の{議題|ぎだい}は{三|みっ}つございます。",
          romaji: "Honjitsu no gidai wa mittsu gozaimasu.",
          en: "“We have three items on today's agenda.”",
          literal: "Lit. “Today's agenda items, there are three.”",
          usage: "Framing the count up front helps everyone track progress. Swap 三つ for the real number.",
          tag: "Framing",
        },
        {
          type: "vocab",
          kicker: "Phrase 4 of 4",
          jp: "{何|なに}かご{質問|しつもん}はございますか。",
          romaji: "Nanika go-shitsumon wa gozaimasu ka.",
          en: "“Are there any questions?”",
          literal: "Lit. “Do any questions exist?” (polite)",
          usage: "Opens the floor after a point. Pausing here, rather than ploughing on, signals you value the room's input.",
          tag: "Inviting",
        },
        {
          type: "dialogue",
          kicker: "In context",
          title: "Calling the meeting to order",
          speakerA: "司会",
          speakerB: "",
          lines: [
            { who: "a", jp: "それでは、{始|はじ}めさせていただきます。", note: "Humble start" },
            { who: "a", jp: "{本日|ほんじつ}はお{忙|いそが}しい{中|なか}、ありがとうございます。", note: "Thanking the room" },
            { who: "a", jp: "{本日|ほんじつ}の{議題|ぎだい}は{三|みっ}つございます。", note: "Framing the agenda" },
          ],
          caption: "Three moves in ten seconds: begin humbly, thank the room, then frame what's ahead. The meeting now has a shape everyone can follow.",
        },
        {
          type: "quiz-arrange",
          kicker: "Quick check",
          q: "Build the humble way to start: “Well then, allow me to begin.”",
          target: ["それでは、", "{始|はじ}め", "させて", "いただきます。"],
          romaji: "Sore dewa, hajimesasete itadakimasu.",
          en: "“Well then, allow me to begin.”",
          explain: "それでは → 始め → させて → いただきます。 The 〜させていただく frame casts starting as something the room graciously permits.",
        },
      ],
    },

    "meet-opinion": {
      moduleId: "meetings",
      index: 2,
      total: 2,
      title: "Opinions & Disagreement",
      jp: "{意見|いけん}と{反対|はんたい}",
      summary: "Pushing back without breaking the room's harmony.",
      cards: [
        {
          type: "intro",
          kicker: "Meetings · Opinions",
          title: "Disagreeing without a “no”",
          body: "Direct contradiction is rare in a Japanese meeting. The skill is to acknowledge the other view first, then introduce your own as an addition rather than a rejection. Done well, it never feels like conflict.",
          meta: "4 phrases · 1 example · 1 check",
        },
        {
          type: "concept",
          kicker: "The rule",
          title: "Acknowledge, soften, then add",
          points: [
            { k: "Acknowledge", v: "Grant their point first: おっしゃる通りですが…" },
            { k: "Soften", v: "Frame yours as a personal view: 私としては…" },
            { k: "Defer", v: "If unresolved, buy time: 持ち帰って検討いたします。" },
          ],
          note: "“Yes, and” lands; a flat いいえ rarely does. Disagreement is built as an extension of agreement.",
        },
        {
          type: "vocab",
          kicker: "Phrase 1 of 4",
          jp: "おっしゃる{通|とお}りですが、",
          romaji: "Ossharu tōri desu ga,",
          en: "“You're quite right, but…”",
          literal: "Lit. “It is exactly as you (honorably) say, but…”",
          usage: "おっしゃる is the honorific of 言う. You concede their point fully before the trailing が pivots to your own view.",
          tag: "Acknowledging",
        },
        {
          type: "vocab",
          kicker: "Phrase 2 of 4",
          jp: "{私|わたくし}としては、〜と{考|かんが}えております。",
          romaji: "Watakushi to shite wa, ... to kangaete orimasu.",
          en: "“Personally, I think that…”",
          literal: "Lit. “As for me, I am thinking that…”",
          usage: "私 read わたくし is the formal first person. Framing it as your own view makes a different opinion feel less like a challenge.",
          tag: "Your view",
        },
        {
          type: "vocab",
          kicker: "Phrase 3 of 4",
          jp: "{一点|いってん}、{確認|かくにん}させていただけますか。",
          romaji: "Itten, kakunin sasete itadakemasu ka.",
          en: "“May I confirm one point?”",
          literal: "Lit. “One point, may I be allowed to confirm?”",
          usage: "A gentle way to raise a doubt: you frame it as checking your own understanding rather than challenging theirs.",
          tag: "Probing",
        },
        {
          type: "vocab",
          kicker: "Phrase 4 of 4",
          jp: "{持|も}ち{帰|かえ}って{検討|けんとう}いたします。",
          romaji: "Mochikaette kentō itashimasu.",
          en: "“I'll take it back and consider it.”",
          literal: "Lit. “I will carry it home and examine it.”",
          usage: "The polite way to avoid committing on the spot. It signals seriousness without yes or no, and is fully respectable.",
          tag: "Deferring",
        },
        {
          type: "dialogue",
          kicker: "In context",
          title: "Pushing back gently",
          speakerA: "あなた",
          speakerB: "",
          lines: [
            { who: "a", jp: "おっしゃる{通|とお}りですが、", note: "Concede first" },
            { who: "a", jp: "{私|わたくし}としては、{納期|のうき}が{心配|しんぱい}です。", note: "Your view, softly framed" },
            { who: "a", jp: "{一度|いちど}{持|も}ち{帰|かえ}って{検討|けんとう}いたします。", note: "Defer rather than clash" },
          ],
          caption: "The disagreement never appears as “no.” It's an acknowledgement, a personal worry, and an offer to think further.",
        },
        {
          type: "quiz-mc",
          kicker: "Quick check",
          q: "A senior colleague proposes a deadline you think is too tight. What's the most natural first move?",
          options: [
            { jp: "おっしゃる{通|とお}りですが、", correct: true },
            { jp: "いいえ、{無理|むり}です。", correct: false },
            { jp: "{違|ちが}います。", correct: false },
          ],
          explain: "You open by granting their point with おっしゃる通りですが, then pivot. A flat いいえ or 違います would feel blunt and confrontational.",
        },
      ],
    },

    "phone-basics": {
      moduleId: "phone",
      index: 1,
      total: 2,
      title: "Handling the Phone",
      jp: "{電話|でんわ}{応対|おうたい}",
      summary: "Identifying, holding, and promising a call back, with no body language to help.",
      cards: [
        {
          type: "intro",
          kicker: "Phone · Basics",
          title: "Politeness you can't see",
          body: "On the phone there's no bow and no business card, so the spoken formulas carry the whole weight of politeness. The first rule: identify your company before anything else, and keep the register high throughout.",
          meta: "4 phrases · 1 example · 1 check",
        },
        {
          type: "concept",
          kicker: "The rule",
          title: "Name the company, then serve",
          points: [
            { k: "Answer", v: "Open with thanks and your company: お電話ありがとうございます。株式会社アオイでございます。" },
            { k: "Hold", v: "Never go silent: 少々お待ちください。" },
            { k: "Your side", v: "Speak humbly about your own colleagues: ただいま席を外しております。" },
          ],
          note: "Inside your company everyone, even the president, is referred to humbly when you speak to an outsider.",
        },
        {
          type: "vocab",
          kicker: "Phrase 1 of 4",
          jp: "お{電話|でんわ}ありがとうございます。",
          romaji: "O-denwa arigatō gozaimasu.",
          en: "“Thank you for calling.”",
          literal: "Lit. “Thank you for the honorable phone call.”",
          usage: "The standard answer, said before you give the company name. Many firms expect it within three rings.",
          tag: "Answering",
        },
        {
          type: "vocab",
          kicker: "Phrase 2 of 4",
          jp: "{少々|しょうしょう}お{待|ま}ちください。",
          romaji: "Shōshō o-machi kudasai.",
          en: "“One moment, please.”",
          literal: "Lit. “Please wait a short while.”",
          usage: "少々 is the formal 少し. Use it before putting someone on hold; returning, you say お待たせいたしました。",
          tag: "Holding",
        },
        {
          type: "vocab",
          kicker: "Phrase 3 of 4",
          jp: "ただいま{席|せき}を{外|はず}しております。",
          romaji: "Tadaima seki o hazushite orimasu.",
          en: "“He's away from his desk at the moment.”",
          literal: "Lit. “Right now (he) is removing himself from the seat.”",
          usage: "How you describe an absent colleague to an outside caller. おります is humble, because your own side is always lowered to the customer.",
          tag: "Your side",
        },
        {
          type: "vocab",
          kicker: "Phrase 4 of 4",
          jp: "{折|お}り{返|かえ}しお{電話|でんわ}いたします。",
          romaji: "Orikaeshi o-denwa itashimasu.",
          en: "“I'll call you back.”",
          literal: "Lit. “I will humbly return the phone call.”",
          usage: "折り返し means returning the call. Pair it with a time: のちほど折り返しお電話いたします。",
          tag: "Calling back",
        },
        {
          type: "dialogue",
          kicker: "In context",
          title: "Taking a message",
          speakerA: "あなた",
          speakerB: "",
          lines: [
            { who: "a", jp: "お{電話|でんわ}ありがとうございます。{株式会社|かぶしきがいしゃ}アオイでございます。", note: "Thanks, then company" },
            { who: "a", jp: "{申|もう}し{訳|わけ}ございません。{佐藤|さとう}はただいま{席|せき}を{外|はず}しております。", note: "Humble about your colleague" },
            { who: "a", jp: "{戻|もど}り{次第|しだい}、{折|お}り{返|かえ}しお{電話|でんわ}いたします。", note: "Promise a call back" },
          ],
          caption: "Note 佐藤はおります, not いらっしゃいます: your own colleague is lowered when you speak to an outside caller, even if he outranks you.",
        },
        {
          type: "quiz-match",
          kicker: "Quick check",
          q: "Match each phone phrase to its job.",
          pairs: [
            { jp: "{少々|しょうしょう}お{待|ま}ちください。", en: "Putting the caller on hold" },
            { jp: "ただいま{席|せき}を{外|はず}しております。", en: "Colleague is away" },
            { jp: "{折|お}り{返|かえ}しお{電話|でんわ}いたします。", en: "Promising to call back" },
          ],
          explain: "少々お待ちください holds the line, 席を外しております explains an absence humbly, and 折り返し promises a return call.",
        },
      ],
    },

    "phone-keigo": {
      moduleId: "phone",
      index: 2,
      total: 2,
      title: "Honorific & Humble",
      jp: "{尊敬語|そんけいご}・{謙譲語|けんじょうご}",
      summary: "The two ladders of respect, and the verbs that ride them.",
      cards: [
        {
          type: "intro",
          kicker: "Keigo · The two ladders",
          title: "Raising them, lowering you",
          body: "Beyond polite ます-speech sit two parallel systems. 尊敬語 raises the other person by elevating their actions; 謙譲語 lowers you by humbling your own. Many everyday verbs swap to entirely different words, and mixing them up is the classic intermediate slip.",
          meta: "4 phrases · 1 example · 1 check",
        },
        {
          type: "concept",
          kicker: "The rule",
          title: "Same verb, two directions",
          points: [
            { k: "見る see", v: "Their action: ご覧になる. Your action: 拝見する。" },
            { k: "言う say", v: "Their action: おっしゃる. Your action: 申す。" },
            { k: "食べる eat", v: "Their action: 召し上がる. Your action: いただく。" },
          ],
          note: "Honorific is never used about yourself; humble is never used about the other person. The direction is the whole point.",
        },
        {
          type: "vocab",
          kicker: "Pair 1 of 4 · 見る",
          jp: "{拝見|はいけん}いたします。",
          romaji: "Haiken itashimasu.",
          en: "“I'll take a look.” (humble)",
          literal: "Lit. “I humbly look.”",
          usage: "Your own seeing or reading: 資料を拝見いたします。 For their seeing, use the honorific ご覧になる: 資料をご覧になりましたか。",
          tag: "謙譲語",
        },
        {
          type: "vocab",
          kicker: "Pair 2 of 4 · 言う",
          jp: "{申|もう}し{上|あ}げます。",
          romaji: "Mōshi-agemasu.",
          en: "“I say / I tell (you).” (humble)",
          literal: "Lit. “I humbly say up to you.”",
          usage: "Your own speaking: お礼申し上げます。 For their speaking, use おっしゃる: 部長がおっしゃいました。 Never 申す about the other person.",
          tag: "謙譲語",
        },
        {
          type: "vocab",
          kicker: "Pair 3 of 4 · 行く・来る",
          jp: "{伺|うかが}います。",
          romaji: "Ukagaimasu.",
          en: "“I'll come / visit.” (humble)",
          literal: "Lit. “I humbly go/visit.”",
          usage: "Your own going or visiting: 明日そちらに伺います。 For their coming, use いらっしゃる: 部長がいらっしゃいます。",
          tag: "謙譲語",
        },
        {
          type: "vocab",
          kicker: "Pair 4 of 4 · する",
          jp: "いたします。",
          romaji: "Itashimasu.",
          en: "“I do / I will.” (humble)",
          literal: "Lit. “I humbly do.”",
          usage: "Your own doing: 私が担当いたします。 For their doing, use なさる: どうなさいますか。 This pair underlies いたします in nearly every closing.",
          tag: "謙譲語",
        },
        {
          type: "dialogue",
          kicker: "In context",
          title: "One exchange, both ladders",
          speakerA: "あなた / 取引先",
          speakerB: "",
          lines: [
            { who: "a", jp: "{資料|しりょう}は{拝見|はいけん}いたしました。", note: "You: humble 拝見" },
            { who: "a", jp: "{部長|ぶちょう}はもうご{覧|らん}になりましたか。", note: "Them: honorific ご覧になる" },
            { who: "a", jp: "{明日|あす}、そちらに{伺|うかが}います。", note: "You: humble 伺う" },
          ],
          caption: "Watch the direction flip: 拝見 and 伺う lower your own actions, while ご覧になる raises theirs. Same conversation, opposite ladders.",
        },
        {
          type: "quiz-mc",
          kicker: "Quick check",
          q: "You want to ask a client whether they have already read the document. Which verb is correct?",
          options: [
            { jp: "もうご{覧|らん}になりましたか。", correct: true },
            { jp: "もう{拝見|はいけん}しましたか。", correct: false },
            { jp: "もう{見|み}ましたか。", correct: false },
          ],
          explain: "The client's action takes the honorific ご覧になる. 拝見する is humble and only describes your own seeing; plain 見ましたか is too casual for a client.",
        },
      ],
    },
  },
};
